name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: config
      run: cmake -B build
    - name: build
      run: cmake --build build
    - name: test
      run: build/example
